### ISSUE TITLE
연락드릴 수단이 없어서 여기에 씁니다..

### ISSUE THREAD

**Issue by hebrews1010** [leefilll/smart-fridge#1]
냉장고 앱을 만들어보고싶어서요.. 혹시 여기 나오는 음식 재료 아이콘을 사용해도 될까요..?
안된다면 만드신 방법이라도 알려주시면 정말 감사하겠습니다 ㅠㅠㅠ

**Comment by leefilll** [comment]
안녕하세요?
어떻게 이 레포지토리까지 오셨는지는 모르겠지만... 여기 있는 아이콘은 다른 서비스에서도 사용 중이라서 좀 힘들 것 같습니다...
다른 방법으로는 무료 아이콘을 찾아 받아서 출처를 표기하고 사용하는 등의 방법이 있을 것 같습니다.
